rewriting, refactoring and implementation of latest ut port version
softwaregroup-bg/ut-port-ftp pull request #1
Opened 2018-03-16 08:05 UTC by Mitko-G

2018-03-19 05:45 UTC, kalinkrustev commented
Please check the jenkins errors

2018-04-18 09:41 UTC, Mitko-G commented
Errors are fixed

2018-04-24 02:04 UTC, kalinkrustev requested changes

2018-04-24 02:04 UTC, kalinkrustev commented on index.js
> +        this.config = Object.assign({
We have to use lodash.merge when the object we merge into is not flat. 
For example doing
```js
Object.assign({host:'localhost',port:22}, {port: 1000})
```
will overwrite the default host with undefined host.

2018-04-24 12:14 UTC, Mitko-G commented
done

2018-04-25 23:37 UTC, merged